// <auto-generated />
using App_web_Tatry.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_web_Tatry.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617095531_AddAdminTable")]
    partial class AddAdminTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_web_Tatry.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Adminowie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasloHash = "$2a$11$/9SFaCYU2BPy/ywdyWiC/.uYWcnbhdsT6bU06K8GQC7miEQ9g2ifa",
                            Login = "admin"
                        });
                });

            modelBuilder.Entity("App_web_Tatry.Entities.Szlak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CzasPrzejscia")
                        .HasColumnType("float");

                    b.Property<double>("Dlugosc")
                        .HasColumnType("float");

                    b.Property<string>("KolorSzlakow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoziomTrudnosci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Szlaki");
                });

            modelBuilder.Entity("App_web_Tatry.Entities.Zdjecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SciezkaPliku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SzlakId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SzlakId");

                    b.ToTable("Zdjecia");
                });

            modelBuilder.Entity("App_web_Tatry.Entities.Zdjecie", b =>
                {
                    b.HasOne("App_web_Tatry.Entities.Szlak", "Szlak")
                        .WithMany("Zdjecia")
                        .HasForeignKey("SzlakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szlak");
                });

            modelBuilder.Entity("App_web_Tatry.Entities.Szlak", b =>
                {
                    b.Navigation("Zdjecia");
                });
#pragma warning restore 612, 618
        }
    }
}
