// <auto-generated />
using App_web_Tatry.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_web_Tatry.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_web_Tatry.Entities.Szlak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CzasPrzejscia")
                        .HasColumnType("float");

                    b.Property<double>("Dlugosc")
                        .HasColumnType("float");

                    b.Property<string>("KolorSzlakow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoziomTrudnosci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Szlaki");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CzasPrzejscia = 2.5,
                            Dlugosc = 7.7999999999999998,
                            KolorSzlakow = "Czerwony",
                            Nazwa = "Morskie Oko z Palenicy Białczańskiej",
                            Opis = "Najpopularniejszy szlak w Tatrach, idealny dla rodzin z dziećmi. Prowadzi asfaltową drogą wzdłuż malowniczych potoków aż do schroniska nad największym tatrzańskim jeziorem.",
                            PoziomTrudnosci = "Łatwy"
                        });
                });

            modelBuilder.Entity("App_web_Tatry.Entities.Zdjecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SciezkaPliku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SzlakId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SzlakId");

                    b.ToTable("Zdjecia");
                });

            modelBuilder.Entity("App_web_Tatry.Entities.Zdjecie", b =>
                {
                    b.HasOne("App_web_Tatry.Entities.Szlak", "Szlak")
                        .WithMany("Zdjecia")
                        .HasForeignKey("SzlakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szlak");
                });

            modelBuilder.Entity("App_web_Tatry.Entities.Szlak", b =>
                {
                    b.Navigation("Zdjecia");
                });
#pragma warning restore 612, 618
        }
    }
}
